.TH "GMAIL NOTIFIER" "1" "Feb 4, 2010" "" ""
.SH "NAME"
Gmail Notifier \- Simple notification daemon for GMail inboxes
.SH "SYNOPSIS"
.B gmail-notifier
.RI [ options ] 
.br 
.SH "DESCRIPTION"
This manual page documents briefly the
.B gmail-notifier
command.
.PP 
\fBGmail Notifier\fP is a simple program designed to watch GMail accounts
for new mail and notify the user whenever new mail arrives.
.SH "OPTIONS"
\fBGmail Notifier\fP does not recognize any command-line options, except
\fBdebug\fP, which will drastically increase terminal output
.SH "AUTHOR"
\fBGmail Notifier\fP written by Pat Pannuto <pat.pannuto@gmail.com>
.PP 
This manual page was written by Pat Pannuto <pat.pannuto@gmail.com>
for the Ubuntu project (but may be used by others).
